import color from "../../constants/color";
import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'flex-end',
  alignItems: 'center',
},
whiteContainer: {
  flex: 1,
  backgroundColor: '#fff',
  borderTopLeftRadius: 35,
  borderTopRightRadius: 35,
  marginTop: -40, 
  paddingTop: 15,
  shadowColor: 'gray',
  shadowOpacity: 1,
  shadowRadius: 5,
  elevation: 3,  
  borderTopWidth: 5,
  borderTopColor: 'rgba(7, 59, 119, 0.3)', 
},
modalContainer: {
  width: '100%',
  backgroundColor: 'white',
  borderTopLeftRadius: 30,
  borderTopRightRadius: 30,
  paddingVertical: 25,
  paddingHorizontal: 20,
  alignItems: 'center',
  elevation: 15,
},
modalTitle: {
  fontSize: 20,
  fontWeight: '700',
  color: 'black',
  marginBottom: 20,
},
optionButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  width: '85%',
  paddingVertical: 12,
  borderRadius: 15,
  marginVertical: 8,
  elevation: 3,
  shadowColor: '#000',
  shadowOpacity: 0.2,
  shadowRadius: 3,
  gap: 10,
},

optionText: {
  color: 'white',
  fontSize: 16,
  fontWeight: '600',
},

cancelButton: {
  marginTop: 15,
  paddingVertical: 8,
  paddingHorizontal: 30,
  borderRadius: 10,
},
viewMap:
    {
  height: 250,
  width: '98%',
  alignSelf: 'center',
  borderRadius: 20,
  overflow: 'hidden', 
  elevation: 5,  
  top:-13
},
cancelText: {
  color: color.error,
  fontWeight: '800',
  fontSize: 15,
},
  main: { flex: 1, backgroundColor: '#fff' },
gradientContainer: {
  height: 150,
  backgroundColor: color.primary,
  alignItems: 'center',
  justifyContent: 'center',
  borderBottomLeftRadius: 25, 
  borderBottomRightRadius: 25, 
  shadowColor: '#000',        
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 4,
  elevation: 6,   
},
  containerText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: color.textLight,
    marginBottom: 9,
    marginLeft: 15,
  },
  cardContainer: {
    marginTop: 20,
    width: 360,
    alignItems: 'center',
  },
  card: {
    width: '100%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#eee',
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    position: 'relative',
    overflow: 'hidden',
  },
  dateBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: color.primary,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    elevation: 8,
  },
  dateText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '600',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  clientName: { fontSize: 18, fontWeight: '600', color: '#2C3E50' },
  cardAddress: { fontSize: 15, color: '#6B7280', marginTop: 4, fontWeight: '600' },
  cardPurpose: { marginTop: 4, color: '#6B7280', fontWeight: '500' },
  actions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    alignItems: 'center',
  },
  reScheduleButton: {
    width: 120,
    height: 32,
    backgroundColor: 'green',
    justifyContent: 'center',
    borderRadius: 20,
  },
  reScheduleText: {
    color: 'white',
    alignSelf: 'center',
    fontWeight: '600',
    fontSize: 13,
  },
  ion: { marginLeft: 10, marginTop: 8 },
});
